name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # ✅ Install pnpm first (important)
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # ✅ Then set up Node (after pnpm)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ✅ Install dependencies without lockfile
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Install Playwright dependencies
      - run: npx playwright install --with-deps

      # Run Nx tasks (adjust to your workspace setup)
      - run: npx nx run-many -t lint test build e2e

      # Always run fix step even if previous steps fail
      - run: npx nx fix-ci
        if: always()